package io.rebble.libpebblecommon.packets.blobdb

enum class TimelineIcon(val id: UInt, val code: String) {
    NotificationReminder(3u, "system://images/NOTIFICATION_REMINDER"),
    HockeyGame(30u, "system://images/HOCKEY_GAME"),
    PayBill(38u, "system://images/PAY_BILL"),
    NotificationLinkedIn(115u, "system://images/NOTIFICATION_LINKEDIN"),
    NotificationGoogleInbox(61u, "system://images/NOTIFICATION_GOOGLE_INBOX"),
    GenericQuestion(63u, "system://images/GENERIC_QUESTION"),
    NotificationFlag(4u, "system://images/NOTIFICATION_FLAG"),
    GenericSms(45u, "system://images/GENERIC_SMS"),
    WatchDisconnected(48u, "system://images/WATCH_DISCONNECTED"),
    TvShow(73u, "system://images/TV_SHOW"),
    Basketball(74u, "system://images/BASKETBALL"),
    GenericWarning(28u, "system://images/GENERIC_WARNING"),
    LightRain(32u, "system://images/LIGHT_RAIN"),
    NotificationFacebook(11u, "system://images/NOTIFICATION_FACEBOOK"),
    IncomingPhoneCall(78u, "system://images/INCOMING_PHONE_CALL"),
    NotificationGoogleMessenger(76u, "system://images/NOTIFICATION_GOOGLE_MESSENGER"),
    NotificationTelegram(7u, "system://images/NOTIFICATION_TELEGRAM"),
    NotificationFacetime(110u, "system://images/NOTIFICATION_FACETIME"),
    ArrowDown(99u, "system://images/ARROW_DOWN"),
    NotificationOutlook(64u, "system://images/NOTIFICATION_OUTLOOK"),
    NoEvents(57u, "system://images/NO_EVENTS"),
    AudioCassette(12u, "system://images/AUDIO_CASSETTE"),
    Sunset(85u, "system://images/SUNSET"),
    NotificationTwitter(6u, "system://images/NOTIFICATION_TWITTER"),
    Sunrise(84u, "system://images/SUNRISE"),
    HeavyRain(52u, "system://images/HEAVY_RAIN"),
    NotificationMailbox(60u, "system://images/NOTIFICATION_MAILBOX"),
    AmericanFootball(20u, "system://images/AMERICAN_FOOTBALL"),
    CarRental(24u, "system://images/CAR_RENTAL"),
    CricketGame(26u, "system://images/CRICKET_GAME"),
    NotificationWeChat(71u, "system://images/NOTIFICATION_WECHAT"),
    NotificationGeneric(1u, "system://images/NOTIFICATION_GENERIC"),
    NotificationSkype(68u, "system://images/NOTIFICATION_SKYPE"),
    CloudyDay(25u, "system://images/CLOUDY_DAY"),
    DuringPhoneCallCentered(95u, "system://images/DURING_PHONE_CALL_CENTERED"),
    NotificationLine(67u, "system://images/NOTIFICATION_LINE"),
    HotelReservation(31u, "system://images/HOTEL_RESERVATION"),
    NotificationFacebookMessenger(10u, "system://images/NOTIFICATION_FACEBOOK_MESSENGER"),
    NotificationLighthouse(81u, "system://images/NOTIFICATION_LIGHTHOUSE"),
    TimelineEmptyCalendar(96u, "system://images/TIMELINE_EMPTY_CALENDAR"),
    NotificationIosPhotos(114u, "system://images/NOTIFICATION_IOS_PHOTOS"),
    ResultDeleted(43u, "system://images/RESULT_DELETED"),
    NotificationGmail(9u, "system://images/NOTIFICATION_GMAIL"),
    TimelineMissedCall(2u, "system://images/TIMELINE_MISSED_CALL"),
    Sleep(101u, "system://images/SLEEP"),
    ResultMute(46u, "system://images/RESULT_MUTE"),
    NotificationAmazon(111u, "system://images/NOTIFICATION_AMAZON"),
    ThumbsUp(97u, "system://images/THUMBS_UP"),
    ScheduledFlight(54u, "system://images/SCHEDULED_FLIGHT"),
    Settings(83u, "system://images/SETTINGS"),
    PartlyCloudy(37u, "system://images/PARTLY_CLOUDY"),
    StocksEvent(42u, "system://images/STOCKS_EVENT"),
    NotificationGoogleMaps(112u, "system://images/NOTIFICATION_GOOGLE_MAPS"),
    RewardGood(103u, "system://images/REWARD_GOOD"),
    NotificationYahooMail(72u, "system://images/NOTIFICATION_YAHOO_MAIL"),
    BirthdayEvent(23u, "system://images/BIRTHDAY_EVENT"),
    GenericEmail(19u, "system://images/GENERIC_EMAIL"),
    ResultDismissed(51u, "system://images/RESULT_DISMISSED"),
    NotificationGooglePhotos(113u, "system://images/NOTIFICATION_GOOGLE_PHOTOS"),
    TideIsHigh(50u, "system://images/TIDE_IS_HIGH"),
    NotificationViber(70u, "system://images/NOTIFICATION_VIBER"),
    LightSnow(33u, "system://images/LIGHT_SNOW"),
    NewsEvent(36u, "system://images/NEWS_EVENT"),
    GenericConfirmation(55u, "system://images/GENERIC_CONFIRMATION"),
    TimelineSports(17u, "system://images/TIMELINE_SPORTS"),
    NotificationSlack(116u, "system://images/NOTIFICATION_SLACK"),
    CheckInternetConnection(44u, "system://images/CHECK_INTERNET_CONNECTION"),
    Activity(100u, "system://images/ACTIVITY"),
    NotificationHipChat(77u, "system://images/NOTIFICATION_HIPCHAT"),
    NotificationInstagram(59u, "system://images/NOTIFICATION_INSTAGRAM"),
    TimelineBaseball(22u, "system://images/TIMELINE_BASEBALL"),
    RewardBad(102u, "system://images/REWARD_BAD"),
    ReachedFitnessGoal(66u, "system://images/REACHED_FITNESS_GOAL"),
    DaySeparator(56u, "system://images/DAY_SEPARATOR"),
    TimelineCalendar(21u, "system://images/TIMELINE_CALENDAR"),
    RainingAndSnowing(65u, "system://images/RAINING_AND_SNOWING"),
    RadioShow(39u, "system://images/RADIO_SHOW"),
    DismissedPhoneCall(75u, "system://images/DISMISSED_PHONE_CALL"),
    ArrowUp(98u, "system://images/ARROW_UP"),
    RewardAverage(104u, "system://images/REWARD_AVERAGE"),
    MusicEvent(35u, "system://images/MUSIC_EVENT"),
    NotificationSnapchat(69u, "system://images/NOTIFICATION_SNAPCHAT"),
    NotificationBlackberryMessenger(58u, "system://images/NOTIFICATION_BLACKBERRY_MESSENGER"),
    NotificationWhatsapp(5u, "system://images/NOTIFICATION_WHATSAPP"),
    Location(82u, "system://images/LOCATION"),
    SoccerGame(41u, "system://images/SOCCER_GAME"),
    ResultFailed(62u, "system://images/RESULT_FAILED"),
    ResultUnmute(86u, "system://images/RESULT_UNMUTE"),
    ScheduledEvent(40u, "system://images/SCHEDULED_EVENT"),
    TimelineWeather(14u, "system://images/TIMELINE_WEATHER"),
    TimelineSun(16u, "system://images/TIMELINE_SUN"),
    NotificationGoogleHangouts(8u, "system://images/NOTIFICATION_GOOGLE_HANGOUTS"),
    DuringPhoneCall(49u, "system://images/DURING_PHONE_CALL"),
    NotificationKik(80u, "system://images/NOTIFICATION_KIK"),
    ResultUnmuteAlt(94u, "system://images/RESULT_UNMUTE_ALT"),
    MovieEvent(34u, "system://images/MOVIE_EVENT"),
    GlucoseMonitor(29u, "system://images/GLUCOSE_MONITOR"),
    ResultSent(47u, "system://images/RESULT_SENT"),
    AlarmClock(13u, "system://images/ALARM_CLOCK"),
    HeavySnow(53u, "system://images/HEAVY_SNOW"),
    DinnerReservation(27u, "system://images/DINNER_RESERVATION"),
    NotificationKakaoTalk(79u, "system://images/NOTIFICATION_KAKAOTALK"),
    NotificationBeeper(120u, "system://images/NOTIFICATION_BEEPER"),
    NotificationDiscord(121u, "system://images/NOTIFICATION_DISCORD"),
    NotificationBluesky(122u, "system://images/NOTIFICATION_BLUESKY"),
    NotificationDuolingo(123u, "system://images/NOTIFICATION_DUOLINGO"),
    NotificationElement(124u, "system://images/NOTIFICATION_ELEMENT"),
    NotificationGoogleChat(125u, "system://images/NOTIFICATION_GOOGLE_CHAT"),
    NotificationGoogleTasks(126u, "system://images/NOTIFICATION_GOOGLE_TASKS"),
    NotificationHomeAssistant(127u, "system://images/NOTIFICATION_HOME_ASSISTANT"),
    NotificationSteam(128u, "system://images/NOTIFICATION_STEAM"),
    NotificationTeams(129u, "system://images/NOTIFICATION_TEAMS"),
    NotificationThreads(130u, "system://images/NOTIFICATION_THREADS"),
    NotificationUnifiProtect(131u, "system://images/NOTIFICATION_UNIFI_PROTECT"),
    NotificationZoom(132u, "system://images/NOTIFICATION_ZOOM"),
    NotificationEbay(133u, "system://images/NOTIFICATION_EBAY"),
    NotificationYoutube(134u, "system://images/NOTIFICATION_YOUTUBE"),
    NotificationSignal(135u, "system://images/NOTIFICATION_SIGNAL"),
    NotificationTwitch(136u, "system://images/NOTIFICATION_TWITCH"),
    ;

    companion object {
        fun fromId(id: UInt): TimelineIcon {
            return entries.firstOrNull { it.id == id }
                ?: error("Unknown timeline icon id: $id")
        }

        fun TimelineIcon.key() = code.replace("system://images/", "")

        fun fromCode(code: String?): TimelineIcon? = entries.firstOrNull { it.code == code }
    }
}